leftnav:
- identifier: 33354b01-9efc-288b-f777-a602d8417133
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 9f635961-2080-a7da-c78c-40b7d8b1c98c
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: 2e3cddc0-846e-9a39-264b-350202eb9d29
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 932ecf24-f8ea-280c-1c2a-462edb8532dd
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: a68cc946-3bba-56fd-960e-e4dd072fdb15
  name: Exams
  pageRef: /pages/exams
  weight: 50
